### PR TITLE
Handle situations where the search service stops responding

### PR DESCRIPTION
**Pull request by dylanmccall**
This commit changes the search provider to constantly try using the Kolibri API, and only fall back to the local database if it is not responding. This is a change from the previous behaviour where it would test a single time whether the API is available and then only use the API, or only use the local database. With the new behaviour, we solve a problem where the search provider would stop working if a user accessed it shortly before and then shortly after stopping Kolibri.

### CODE REVIEW

**Comment by wjt** [comment]
Perhaps a stupid question: if the search provider knows how to hit the database directly, why does it ever need to use the Kolibri HTTP API?

**Comment by dylanmccall** [comment]
It's a legit question! Using the database directly requires an expensive setup process, which was giving me some particularly sluggish search results. This way we can get faster results at least some of the time. There's certainly a cost / benefit analysis to be done here since it isn't _required_ functionality at the moment, but I think it's simple enough to be worthwhile :)

**Comment by jamalex** [comment]
The [original search service provider](https://github.com/learningequality/org.learningequality.Kolibri/blob/bfc601bd3415dc2ab25fcf7523623fb71aec02c8/src/gnome_search_provider_service.py) didn't use HTTP at all, so that it would still work when Kolibri wasn't running, and (since we were doing socket activation) it wouldn't spin up Kolibri every time a search was made.

Rather than accessing the database directly, however, it was essentially "emulating" the HTTP request (but bypassing the HTTP portion, interfacing directly with the Django REST Framework classes) to get results through the Kolibri API layer, so that it could leverage the [logic in Kolibri](https://github.com/learningequality/kolibri/blob/7312a5353021a22fc7b9701468e470cba5e1c62b/kolibri/core/content/api.py#L695) for showing the most specific search results first but falling back to fuzzier matches, etc. This was instead of having to recreate all of that logic (and DB interface) externally.

>Using the database directly requires an expensive setup process, which was giving me some particularly sluggish search results. 

With the search service being persistent (at least for... some duration?), I would have expected that spinning up the Django machinery would be a one-time cost, and then all search results after that would be zippy? The one exception that could make it particularly slow would be if the server hasn't ever been started before, and it needs to do some initialization of the data directory etc (but with the new flatpak's "preseeding" approach, even that shouldn't take too long).

**Comment by jamalex** [comment]
So it might be good to see what's slowing down the "local" search provider and resolve it there? Is there a clear path to replication? (You mention while the server is starting up or shutting down -- I'm guessing ensuring the socket timeout in the [request logic](https://github.com/learningequality/kolibri-installer-gnome/blob/46678ded33b21b67b64b3225cd457043a945eb7c/src/kolibri_gnome/globals.py#L104) isn't too long might be a factor, since you may be testing the server at a time when the socket is still open but it's not yet/no longer handling HTTP requests)

**Comment by jamalex** [comment]
We can merge this in the meantime, and come back to those broader questions later, if preferred?

**Comment by dylanmccall** [comment]
These are good thoughts and questions :) I'll change this to nix the remote search provider, since it's a bit silly to have this special case which doesn't get used the vast majority of the time. I played with providing a custom Django settings module to make the local search provider start faster, but seems there isn't a whole lot we can do there. Looking at the output of cProfile, most of the time is spent loading heaps of Python modules via `django.setup()`, and it happens either way. (Probably slightly less so if we shrink INSTALLED_APPS to a smaller set, but only very slightly). That would be a good thing to come back to for sure.

**Pull request merged**
